language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
os:
  - linux
dist: bionic
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest

# deploy:
#   provider: pypi
#   username: <username>
#   password: <encrypted password>
#   edge: true # opt in to dpl v2
