language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
os:
  - linux
dist: bionic
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest

# deploy:
#   provider: pypi
#   username: <username>
#   password: <encrypted password>
#   edge: true # opt in to dpl v2
